root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:astro/recommended'
  - 'prettier'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'astro'
ignorePatterns:
  - 'dist/**'
  - 'node_modules/**'
  - '.astro/**'
  - '**/*.d.ts'
  - 'public/**'
rules:
  '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_' }]
  '@typescript-eslint/no-explicit-any': 'warn'
overrides:
  - files:
      - '*.astro'
    parser: 'astro-eslint-parser'
    parserOptions:
      parser: '@typescript-eslint/parser'
      extraFileExtensions: ['.astro']
