name = "exclusive-content"
account_id = "f257f3bcb51db7468b59e147970bcb12"
workers_dev = false
route = "https://webmonetization.org/api/exclusive-content/*"
main = "./src/index.ts"
compatibility_date = "2023-02-13"
zone_id = "d6d84b0542f70af344a84313dedf52dd"
