name = "exclusive-content"
type = "javascript"
account_id = "706b3167d38200892ec8b6e44829a60d"
workers_dev = false
route = "https://webmonetization.org/api/exclusive-content/*"
zone_id = "45fea18e67a3947837b8d9eae64e0fd9"
